feat: Enhance info function and add directory creation logic in repo-create script

diff --git a/src/repo b/src/repo
--- a/src/repo
+++ b/src/repo
@@ -6,6 +6,17 @@
 # Uncomment for debugging
 # set -eox pipefail
 
+function info () {
+
+    case "$1" in
+        info            ) echo "${_name}: [INFO] $2"         ;;
+        error           ) echo "${_name}: [ERROR] $2" exit 1 ;;
+        stop            ) echo "${_name}: [STOP] $2"  exit 0 ;;
+        *               ) return 1                           ;;
+    esac
+
+}
+
 _name="repo"
 
 _baseDir="$(pwd)"
@@ -25,10 +36,11 @@ _arch="$(yq -r '.architectures' "$_yaml")"
 _components="$(yq -r '.components' "$_yaml")"
 _maintainer="$(yq -r '.maintainer' "$_yaml")"
 _description="$(yq -r '.description' "$_yaml")"
+_type=$(yq -r '.sign' "$_yaml")
+_key=$(yq -r '.key' "$_yaml")
 
 for f in $_origin $_label $_suite $_codename $_arch $_components ; do
-    [[ "$f" == "null" ]] && {
-    echo "$_name - [ERROR] $f value in $_yaml!" ; exit 1 ; }
+    [[ "$f" == "null" ]] && info "error" "$f value in $_yaml!"
 done
 
 # Release header
@@ -47,67 +59,73 @@ EOF
 
 # _dists="$(yq -r '.dists[]' "$_yaml")"
 _distsDir="dists/$_suite/$_components"
+_poolDir="pool/$_components"
 
 case "$_arch" in
-    amd64           ) _distsDir+="/binary-$_arch" ;;
-    i386            ) _distsDir+="/binary-$_arch" ;;
-    arm64           ) _distsDir+="/binary-$_arch" ;;
-    all             ) _distsDir+="/binary-$_arch" ;;
-    *               )
-        echo "[ERROR] Unsupported architecture: $_arch" ; exit 1
+    amd64               ) _distsDir+="/binary-$_arch" ;;
+    i386                ) _distsDir+="/binary-$_arch" ;;
+    arm64               ) _distsDir+="/binary-$_arch" ;;
+    all                 ) _distsDir+="/binary-$_arch" ;;
+    *                   )
+        info "error" "Unsupported architecture: $_arch"
+        exit 1
     ;;
 esac
 
-[[ -d "$_distsDir" ]] && echo "[INFO] Compatible dists directory structure"
+[[ -d "$_distsDir" ]] && info "error" "$_distsDir does not exist! Run repo-create first."
+[[ -d "$_poolDir" ]] && info "error" "$_poolDir does not exist! Run repo-create first."
 
-apt-ftparchive packages pool > "$_distsDir/Packages" || {
-echo "[ERROR] Failed to create Packages file!" ; exit 1 ; }
+### Compile package database ###
 
-cd "$_distsDir" || exit 1
+apt-ftparchive packages pool > "$_distsDir/Packages" 2> /dev/null
 
-rm Packages.* || true
+# shellcheck disable=SC2181
+[[ $? -ne 0 ]] && info "error" "Failed to create Packages file!"
 
+info "error" "Packages file created successfully."
+
+rm Packages.* 2> /dev/null && info "info" "Compressing Packages file..."
+
+# shellcheck disable=SC2086
 for _comp in gzip bzip2 xz; do
-    $_comp -k -f Packages
+    $_comp -k -f $_distsDir/Packages
 done
 
-cd - > /dev/null || exit 1
+### Create Release and InRelease files ###
 
 # Create the Release file
 echo "${_releaseFile}" > "dists/$_suite/Release"
 
-apt-ftparchive release dists/stable >> "dists/$_suite/Release" || {
-echo "[ERROR] Failed to create Release file!" ; exit 1 ; }
+apt-ftparchive release dists/stable >> "dists/$_suite/Release"
+
+# shellcheck disable=SC2181
+[[ $? -ne 0 ]] && info "error" "Failed to create Release file!"
+
+info "info" "Release file created successfully."
 
 sed -i '/Release/d' "dists/$_suite/Release"
 
-_type=$(yq -r '.sign' "$_yaml")
-_key=$(yq -r '.key' "$_yaml")
-
 # Check if signing is enabled in the config file.
-[[ "$(yq -r '.sign' "$_yaml")" == "false" ]] && exit 0
+[[ "$(yq -r '.sign' "$_yaml")" == "false" ]] &&
+info "stop" "Signing is disabled in the config file. Exiting..."
 
 rm "dists/$_suite/Release.gpg" "dists/$_suite/InRelease" || true
 
-if [[ -z "$_key" || "$_key" = "null" ]] ; then
-    echo "[ERROR] No GPG key fingerprint specified in config.yaml!"
-    exit 1
-fi
+[[ -z "$_key" || "$_key" = "null" ]] &&
+info "error" "GPG key not specified in the config file!"
 
-! gpg --list-secret-keys "$_key" &> /dev/null && {
-echo "[ERROR] GPG key $_key not found in your keyring!" ; exit 1 ; }
+gpg --list-secret-keys "$_key" &> /dev/null &&
+info "error" "GPG key $_key not found in the keyring!"
 
 gpg \
     --default-key "$_key" \
     --output "dists/$_suite/Release.gpg" \
-    --detach-sig "dists/$_suite/Release" 2> /dev/null
-# shellcheck disable=SC2181
-[[ $? -ne 0 ]] && { echo "[ERROR] Failed to sign the Release file!" ; exit 1 ; }
-
+    --detach-sig "dists/$_suite/Release" 2> /dev/null &&
 gpg \
     --default-key "$_key" \
     --clearsign \
     -o "dists/$_suite/InRelease" "dists/$_suite/Release" 2> /dev/null
+
 # shellcheck disable=SC2181
 [[ $? -ne 0 ]] && { echo "[ERROR] Failed to create InRelease file!" ; exit 1 ; }
 
